### ISSUE TITLE
Master function BUG !

### ISSUE THREAD

**Issue by ml271** [modche/datacourse2018#26]
allright it really sad but the master function is not working any more. i think maybe there where to many changes in the different indices function made. i tryed to figure out where the mistake is but now i really dont have the time anymore to look further. maybe someone can help.

**Comment by modche** [comment]
I started to have a closer look but there are more issues with that functions, e.g. [link](https://github.com/modche/datacourse2018/commit/6ca83d137996d7942540d0f2c9a8a75bf65dd641)
