### ISSUE TITLE
Issue with R95T function

### ISSUE THREAD

**Issue by schneeregen123** [modche/datacourse2018#8]
please remove the hardcoded path to your text-file. It makes `source(R95T.R)` throw an error :-)

**Comment by mmaelicke** [comment]
To the group which wrote this function:
In the utils folder you will find an example of a main.R script, that loads a `genericFunction` from a `generic_functions.R` file. Maybe this helps you to solve path setting problems...

**Comment by modche** [comment]
I have informed the group about this issue/bug.

**Comment by davmen23** [comment]
did I solve the problem? - there should be an updated function (same name)

**Comment by modche** [comment]
So far the version is the same. I think you have to "commit" your changes in Github so that we can accept your `pull request`. Or you send me your updated version via E-Mail. Thanks.

**Comment by modche** [comment]
@schneeregen123 Group provided update. Please check if the function is now working for you.

**Comment by schneeregen123** [comment]
Works great, thank you
